blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://muhammad-fiaz.github.io/httpx.zig/
    about: Read the official documentation and guides.
  - name: GitHub Discussions
    url: https://github.com/muhammad-fiaz/httpx.zig/discussions
    about: Ask questions and discuss with the community.
